Navigation bar with components, imports order, form.range for age and navbars components
darrubla/mir_final_project pull request #11
Opened 2023-08-02 20:34 UTC by C4rlos9559

2023-08-02 20:46 UTC, darrubla requested changes
Dejé unos comentarios para revisar 😁, del resto, buen trabajo

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/CoursesList/CoursesList.jsx
>  import PropTypes from 'prop-types'
por qué eliminas react de acá ? se supone que la librería de react se necesita para poder renderizar el JSX

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/IconBar.jsx
> +        </>
no son necesarios los fragments si solo renderizas un único elemento

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/NavSeparator.jsx
> +        </>
igual acá, si es un solo elemento de primer nivel, no son necesarios los fragments

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/NavigationTab.jsx
> +        </>
acá lo mismo de los fragments

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/StudentNavbar.jsx
> +        </>
acá los fragments

2023-08-02 20:46 UTC, darrubla commented on main react/src/components/TeacherNavbar.jsx
> +        </>
fragments

2023-08-02 20:46 UTC, darrubla commented on main react/src/pages/Signin.jsx
> +    const type = user === undefined ? JSON.parse(localStorage.getItem('user')).type : JSON.parse(JSON.stringify(user)).type;
acá si user es undefined, no es necesario el JSON.parse, significa que no se ha logueado

2023-08-02 20:46 UTC, darrubla commented on main react/src/pages/StudentAccountInfo.jsx
> +    )
acá tampoco necesitas el fragment

2023-08-02 20:46 UTC, darrubla commented on main react/src/pages/Welcome.jsx
> +        </>
aquí tampoco necesitas el fragment

2023-08-02 23:14 UTC, C4rlos9559 commented on main react/src/pages/Signin.jsx
> +    const type = user === undefined ? JSON.parse(localStorage.getItem('user')).type : JSON.parse(JSON.stringify(user)).type;
Lo que pasa es que si se ingresa a la página se signin o signup, si se recarga la página, user queda en undefined y no muestra nada, entonces con el JSON.parse, lee el valor que haya en localStorage y así se evita ese problema.

2023-08-02 23:23 UTC, C4rlos9559 reviewed
Fragments deleted

2023-08-03 14:12 UTC, endyleyms approved these changes
muy buen trabajo, me registre en la pagina por si ven por ahi un usuario nuevo.

2023-08-04 14:52 UTC, darrubla approved these changes

2023-08-04 14:52 UTC, merged